const menuItems =
  [
    {
      name: 'VIEW EVENTS',
      path: '/events'
    },
    {
      name: 'GALLERY',
      path: '/photogallery'
    },
    {
      name: 'ARCHIVE',
      path: '/'
    },
    {
      name: 'HOTELS',
      path: 'https://lasvegas.electricdaisycarnival.com/travel/hotels/'
    },
    {
      name: 'EDC LAS VEGAS',
      path: 'https://lasvegas.electricdaisycarnival.com/'
    }
  ];

export default menuItems;

// const artists = [
//   'above & beyond',
//   'aerial grey',
//   'alan walker',
//   'alesso',
//   'ann clue',
//   'armin van buuren',
//   'artbat',
//   'atliens',
//   'bad beat',
//   'bart skils',
//   'basscon pool party',
//   'bassrush pool party',
//   'bastian bux',
//   'ben finx',
//   'blunts & blondes',
//   'boris brejcha',
//   'brett rubin',
//   'cash cash',
//   'the chainsmokers',
//   'charly jordan',
//   'cheyenne giles',
//   'chris garcia',
//   'chris lake',
//   'christopher james',
//   'claptone',
//   'cloonee',
//   'code black',
//   'crespo',
//   'deadmau5',
//   'delta heavy',
//   'deorro',
//   'deux twins',
//   'diplo',
//   'dj pauly d',
//   'dj snake',
//   'dom dolla',
//   'dombresky',
//   'dr phunk',
//   'edc week afterhours',
//   'elrow',
//   'eric d-lux',
//   'factory 93',
//   'fisher',
//   'flosstradamus',
//   'franklyn watts',
//   'g-eazy',
//   'gta',
//   'harry romero',
//   'honeyluv',
//   'illenium',
//   'imanu',
//   'inigo vontier',
//   'jauz',
//   'jessica audiffred',
//   'john summit',
//   'joshwa',
//   'justin credible',
//   'justin mylo',
//   'kaskade',
//   'kreation',
//   'lny tnz',
//   'loud luxury',
//   'lucky lou',
//   'mad dog',
//   'marshmello',
//   'martin garrix',
//   'meduza',
//   'moritz hofbauer (live)',
//   'murda beatz',
//   'nightmre',
//   'nick warren',
//   'nightstalker',
//   'nora en pure',
//   'partiboi69',
//   'porter robinson',
//   'rated r',
//   'riley bee',
//   'scooter and lavelle',
//   'scotty boy',
//   'sidepiece',
//   'steve aoki',
//   'steve walker',
//   'suae',
//   'tchami',
//   'techno taco tuesday',
//   'tiesto',
//   'timmy trumpet',
//   'tini gessler',
//   'tinlicker',
//   'tnt',
//   'tris tiffany',
//   'troyboi',
//   'tyga',
//   'vintage culture',
//   'william black',
//   'xenaa',
//   'yellow claw'
// ];
